# Generated by Django 5.2.15 on 2026-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('owner', 'Керівник команди'), ('developer', 'Розробник'), ('tester', 'Тестувальник'), ('viewer', 'Переглядач')], default='developer', max_length=20),
        ),
    ]
