# Generated by Django 5.2.15 on 2026-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
    ]
