# Generated by Django 5.2.15 on 2026-06-12 15:26

import chats.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_comment_attachments/%Y/%m/%d/', validators=[chats.models.validate_chat_attachment])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='task_comment_attachments/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.comment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
