# Generated by Django 5.2.15 on 2026-06-12 09:57

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_privatechat_privatemessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private_chat_attachments/%Y/%m/%d/', validators=[chats.models.validate_chat_attachment]),
        ),
    ]
