# Generated by Django 5.2.15 on 2026-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_privatemessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/thumbnails/'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='private_chat_attachments/thumbnails/'),
        ),
    ]
