# Generated by Django 5.2.15 on 2026-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_actor_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_started', 'Task started'), ('task_submitted', 'Task submitted'), ('task_approved', 'Task approved'), ('task_rejected', 'Task rejected'), ('task_updated', 'Task updated'), ('task_commented', 'Task commented'), ('deadline_soon', 'Deadline soon'), ('task_overdue', 'Task overdue')], default='task_updated', max_length=50),
        ),
    ]
